package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "actividad", catalog = "acm")
public class Actividad implements java.io.Serializable {

	private static final long serialVersionUID = -8201276481179092402L;
	private Integer idActividad;
	private Lugar lugar;
	private TipoActividad tipoActividad;
	private String nombreActividad;
	private Date fechaInicio;
	private Date fechaFin;
	private String observaciones;
	private Set<Jornada> jornadas = new HashSet<Jornada>(0);
	private Set<RelActividadParticipante> relActividadParticipantes = new HashSet<RelActividadParticipante>(0);

	public Actividad() {
	}

	public Actividad(String nombreActividad, Date fechaInicio, Date fechaFin) {
		this.nombreActividad = nombreActividad;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Actividad(Lugar lugar, TipoActividad tipoActividad, String nombreActividad, Date fechaInicio, Date fechaFin,
			String observaciones, Set<Jornada> jornadas,
			Set<RelActividadParticipante> relActividadParticipantes) {
		this.lugar = lugar;
		this.tipoActividad = tipoActividad;
		this.nombreActividad = nombreActividad;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.observaciones = observaciones;
		this.jornadas = jornadas;
		this.relActividadParticipantes = relActividadParticipantes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ACTIVIDAD", unique = true, nullable = false)
	public Integer getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(Integer idActividad) {
		this.idActividad = idActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_lugar")
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_actividad")
	public TipoActividad getTipoActividad() {
		return this.tipoActividad;
	}

	public void setTipoActividad(TipoActividad tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	@Column(name = "NOMBRE_ACTIVIDAD", nullable = false)
	public String getNombreActividad() {
		return this.nombreActividad;
	}

	public void setNombreActividad(String nombreActividad) {
		this.nombreActividad = nombreActividad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", nullable = false, length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FIN", nullable = false, length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "OBSERVACIONES", length = 16777215)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividad")
	public Set<Jornada> getJornadas() {
		return this.jornadas;
	}

	public void setJornadas(Set<Jornada> jornadas) {
		this.jornadas = jornadas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividad")
	public Set<RelActividadParticipante> getRelActividadParticipantes() {
		return this.relActividadParticipantes;
	}

	public void setRelActividadParticipantes(Set<RelActividadParticipante> relActividadParticipantes) {
		this.relActividadParticipantes = relActividadParticipantes;
	}

}
