package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jornada generated by hbm2java
 */
@Entity
@Table(name = "jornada", catalog = "acm_schema")
public class Jornada implements java.io.Serializable {

	private Integer idJornada;
	private Actividad actividad;
	private Date fecha;
	private Date horaIncio;
	private String horaFin;

	public Jornada() {
	}

	public Jornada(Date fecha) {
		this.fecha = fecha;
	}

	public Jornada(Actividad actividad, Date fecha, Date horaIncio, String horaFin) {
		this.actividad = actividad;
		this.fecha = fecha;
		this.horaIncio = horaIncio;
		this.horaFin = horaFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_jornada", unique = true, nullable = false)
	public Integer getIdJornada() {
		return this.idJornada;
	}

	public void setIdJornada(Integer idJornada) {
		this.idJornada = idJornada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad")
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_incio", length = 8)
	public Date getHoraIncio() {
		return this.horaIncio;
	}

	public void setHoraIncio(Date horaIncio) {
		this.horaIncio = horaIncio;
	}

	@Column(name = "hora_fin", length = 45)
	public String getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}

}
