package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Participante generated by hbm2java
 */
@Entity
@Table(name = "participante", catalog = "acm_schema")
public class Participante implements java.io.Serializable {

	private Integer idParticipante;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private Date fechaNacimiento;
	private String telefono;
	private String email;
	private Set<RelActividadParticipante> relActividadParticipantes = new HashSet<RelActividadParticipante>(0);
	private Set<RelParticipanteTutor> relParticipanteTutors = new HashSet<RelParticipanteTutor>(0);

	public Participante() {
	}

	public Participante(String nombre) {
		this.nombre = nombre;
	}

	public Participante(String nombre, String apellido1, String apellido2, Date fechaNacimiento, String telefono,
			String email, Set<RelActividadParticipante> relActividadParticipantes,
			Set<RelParticipanteTutor> relParticipanteTutors) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.fechaNacimiento = fechaNacimiento;
		this.telefono = telefono;
		this.email = email;
		this.relActividadParticipantes = relActividadParticipantes;
		this.relParticipanteTutors = relParticipanteTutors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PARTICIPANTE", unique = true, nullable = false)
	public Integer getIdParticipante() {
		return this.idParticipante;
	}

	public void setIdParticipante(Integer idParticipante) {
		this.idParticipante = idParticipante;
	}

	@Column(name = "NOMBRE", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO1")
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "APELLIDO2")
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_NACIMIENTO", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "TELEFONO", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "participante")
	public Set<RelActividadParticipante> getRelActividadParticipantes() {
		return this.relActividadParticipantes;
	}

	public void setRelActividadParticipantes(Set<RelActividadParticipante> relActividadParticipantes) {
		this.relActividadParticipantes = relActividadParticipantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "participante")
	public Set<RelParticipanteTutor> getRelParticipanteTutors() {
		return this.relParticipanteTutors;
	}

	public void setRelParticipanteTutors(Set<RelParticipanteTutor> relParticipanteTutors) {
		this.relParticipanteTutors = relParticipanteTutors;
	}

}
