package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelActividadParticipante generated by hbm2java
 */
@Entity
@Table(name = "rel_actividad_participante", catalog = "acm")
public class RelActividadParticipante implements java.io.Serializable {

	private RelActividadParticipanteId id;
	private Actividad actividad;
	private Participante participante;
	private Double numMetros;
	private Double importe;
	private Integer lgPagado;

	public RelActividadParticipante() {
	}

	public RelActividadParticipante(RelActividadParticipanteId id, Actividad actividad, Participante participante) {
		this.id = id;
		this.actividad = actividad;
		this.participante = participante;
	}

	public RelActividadParticipante(RelActividadParticipanteId id, Actividad actividad, Participante participante,
			Double numMetros, Double importe, Integer lgPagado) {
		this.id = id;
		this.actividad = actividad;
		this.participante = participante;
		this.numMetros = numMetros;
		this.importe = importe;
		this.lgPagado = lgPagado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idActividad", column = @Column(name = "ID_ACTIVIDAD", nullable = false)),
			@AttributeOverride(name = "idParticipante", column = @Column(name = "ID_PARTICIPANTE", nullable = false)) })
	public RelActividadParticipanteId getId() {
		return this.id;
	}

	public void setId(RelActividadParticipanteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTIVIDAD", nullable = false, insertable = false, updatable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARTICIPANTE", nullable = false, insertable = false, updatable = false)
	public Participante getParticipante() {
		return this.participante;
	}

	public void setParticipante(Participante participante) {
		this.participante = participante;
	}

	@Column(name = "NUM_METROS", precision = 22, scale = 0)
	public Double getNumMetros() {
		return this.numMetros;
	}

	public void setNumMetros(Double numMetros) {
		this.numMetros = numMetros;
	}

	@Column(name = "IMPORTE", precision = 22, scale = 0)
	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	@Column(name = "LG_PAGADO")
	public Integer getLgPagado() {
		return this.lgPagado;
	}

	public void setLgPagado(Integer lgPagado) {
		this.lgPagado = lgPagado;
	}

}
