package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelActividadParticipanteId generated by hbm2java
 */
@Embeddable
public class RelActividadParticipanteId implements java.io.Serializable {

	private int idActividad;
	private int idParticipante;

	public RelActividadParticipanteId() {
	}

	public RelActividadParticipanteId(int idActividad, int idParticipante) {
		this.idActividad = idActividad;
		this.idParticipante = idParticipante;
	}

	@Column(name = "ID_ACTIVIDAD", nullable = false)
	public int getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(int idActividad) {
		this.idActividad = idActividad;
	}

	@Column(name = "ID_PARTICIPANTE", nullable = false)
	public int getIdParticipante() {
		return this.idParticipante;
	}

	public void setIdParticipante(int idParticipante) {
		this.idParticipante = idParticipante;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelActividadParticipanteId))
			return false;
		RelActividadParticipanteId castOther = (RelActividadParticipanteId) other;

		return (this.getIdActividad() == castOther.getIdActividad())
				&& (this.getIdParticipante() == castOther.getIdParticipante());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdActividad();
		result = 37 * result + this.getIdParticipante();
		return result;
	}

}
