package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelParticipanteTutorId generated by hbm2java
 */
@Embeddable
public class RelParticipanteTutorId implements java.io.Serializable {

	private int idParticipante;
	private int idTutor;

	public RelParticipanteTutorId() {
	}

	public RelParticipanteTutorId(int idParticipante, int idTutor) {
		this.idParticipante = idParticipante;
		this.idTutor = idTutor;
	}

	@Column(name = "id_participante", nullable = false)
	public int getIdParticipante() {
		return this.idParticipante;
	}

	public void setIdParticipante(int idParticipante) {
		this.idParticipante = idParticipante;
	}

	@Column(name = "id_tutor", nullable = false)
	public int getIdTutor() {
		return this.idTutor;
	}

	public void setIdTutor(int idTutor) {
		this.idTutor = idTutor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelParticipanteTutorId))
			return false;
		RelParticipanteTutorId castOther = (RelParticipanteTutorId) other;

		return (this.getIdParticipante() == castOther.getIdParticipante())
				&& (this.getIdTutor() == castOther.getIdTutor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdParticipante();
		result = 37 * result + this.getIdTutor();
		return result;
	}

}
