package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Socio generated by hbm2java
 */
@Entity
@Table(name = "socio", catalog = "acm")
public class Socio implements java.io.Serializable {

	private Integer idSocio;
	private TipoCargoSocio tipoCargoSocio;
	private String nombreSocio;
	private String apellido1Socio;
	private String apellido2Socio;
	private String correo;
	private String telefono;

	public Socio() {
	}

	public Socio(String nombreSocio) {
		this.nombreSocio = nombreSocio;
	}

	public Socio(TipoCargoSocio tipoCargoSocio, String nombreSocio, String apellido1Socio, String apellido2Socio,
			String correo, String telefono) {
		this.tipoCargoSocio = tipoCargoSocio;
		this.nombreSocio = nombreSocio;
		this.apellido1Socio = apellido1Socio;
		this.apellido2Socio = apellido2Socio;
		this.correo = correo;
		this.telefono = telefono;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_socio", unique = true, nullable = false)
	public Integer getIdSocio() {
		return this.idSocio;
	}

	public void setIdSocio(Integer idSocio) {
		this.idSocio = idSocio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cargo")
	public TipoCargoSocio getTipoCargoSocio() {
		return this.tipoCargoSocio;
	}

	public void setTipoCargoSocio(TipoCargoSocio tipoCargoSocio) {
		this.tipoCargoSocio = tipoCargoSocio;
	}

	@Column(name = "nombre_socio", nullable = false, length = 45)
	public String getNombreSocio() {
		return this.nombreSocio;
	}

	public void setNombreSocio(String nombreSocio) {
		this.nombreSocio = nombreSocio;
	}

	@Column(name = "apellido1_socio", length = 45)
	public String getApellido1Socio() {
		return this.apellido1Socio;
	}

	public void setApellido1Socio(String apellido1Socio) {
		this.apellido1Socio = apellido1Socio;
	}

	@Column(name = "apellido2_socio", length = 45)
	public String getApellido2Socio() {
		return this.apellido2Socio;
	}

	public void setApellido2Socio(String apellido2Socio) {
		this.apellido2Socio = apellido2Socio;
	}

	@Column(name = "correo", length = 45)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
