package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCargoSocio generated by hbm2java
 */
@Entity
@Table(name = "tipo_cargo_socio", catalog = "acm_schema")
public class TipoCargoSocio implements java.io.Serializable {

	private int idCargo;
	private String descripcion;
	private Set<Socio> socios = new HashSet<Socio>(0);

	public TipoCargoSocio() {
	}

	public TipoCargoSocio(int idCargo) {
		this.idCargo = idCargo;
	}

	public TipoCargoSocio(int idCargo, String descripcion, Set<Socio> socios) {
		this.idCargo = idCargo;
		this.descripcion = descripcion;
		this.socios = socios;
	}

	@Id

	@Column(name = "id_cargo", unique = true, nullable = false)
	public int getIdCargo() {
		return this.idCargo;
	}

	public void setIdCargo(int idCargo) {
		this.idCargo = idCargo;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCargoSocio")
	public Set<Socio> getSocios() {
		return this.socios;
	}

	public void setSocios(Set<Socio> socios) {
		this.socios = socios;
	}

}
