package es.acm.entities;
// Generated 06-ene-2018 19:38:01 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tutor generated by hbm2java
 */
@Entity
@Table(name = "tutor", catalog = "acm")
public class Tutor implements java.io.Serializable {

	private Integer idTutor;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String telefono;
	private String mail;
	private Set<RelParticipanteTutor> relParticipanteTutors = new HashSet<RelParticipanteTutor>(0);

	public Tutor() {
	}

	public Tutor(String nombre, String apellido1, String apellido2, String telefono, String mail,
			Set<RelParticipanteTutor> relParticipanteTutors) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.telefono = telefono;
		this.mail = mail;
		this.relParticipanteTutors = relParticipanteTutors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tutor", unique = true, nullable = false)
	public Integer getIdTutor() {
		return this.idTutor;
	}

	public void setIdTutor(Integer idTutor) {
		this.idTutor = idTutor;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", length = 100)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 100)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "mail", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutor")
	public Set<RelParticipanteTutor> getRelParticipanteTutors() {
		return this.relParticipanteTutors;
	}

	public void setRelParticipanteTutors(Set<RelParticipanteTutor> relParticipanteTutors) {
		this.relParticipanteTutors = relParticipanteTutors;
	}

}
